#!/bin/bash

function abs_path {
  (cd "$(dirname '$1')" &>/dev/null && printf "%s/%s" "$PWD" "${1##*/}")
}

if [[ $# != 3 ]]; then
  echo "Expected trusty/xenial/centos6 <dir> <name>" >&2
  exit 1
fi


RELEASE=$1
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PACKAGES_DIR="$DIR/$2"
PACKAGE=$3
if [[ ! -d "$PACKAGES_DIR" ]]; then
  echo "No such directory: $PACKAGES_DIR" >&2
  exit 2
fi

set -x
docker run --rm \
  --privileged \
  -e LOCAL_USER_ID=$(id -u $USER) \
  -v "$PACKAGES_DIR":/vagrant \
  -v "$DIR"/include:/vagrant/include \
  thehyve/buildenv-fpm:"$RELEASE" \
  bash -c "{ ! which apt-get || sudo apt-get update; } && cd /vagrant/'$PACKAGE' && make"
