# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2:

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  codename = ENV['XENIAL'] ? 'xenial' : 'trusty'

  config.vm.box = codename == 'xenial' ? 'xenial-provisional' : "ubuntu/#{codename}64"

  provision_script = <<-eos
    apt-key adv --keyserver keyserver.ubuntu.com --recv 3375DA21
    echo deb http://apt.thehyve.net/internal/ #{codename} main > /etc/apt/sources.list.d/internal.list
    apt-get update
    apt-get install -y ruby-dev bsdtar
    gem install fpm
  eos

	config.vm.provision "shell", inline: provision_script

	config.vm.synced_folder "../include/", "/vagrant/include"

	config.vm.provider "virtualbox" do |v|
		v.cpus = 4
    v.memory = 4096
	end
end
