# vi: set ft=ruby ts=2 sw=2 si et:

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6.4"

  config.vm.provider "virtualbox" do |v|
		v.cpus = 4
		v.memory = 3000
	end

  config.vm.provision :shell, :path => "shell/bootstrap.sh"
  config.vm.provision "puppet"
end
