# vi: set ft=ruby ts=2 sw=2 si et:

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if ENV['UBUNTU']
    config.vm.box = 'ubuntu/trusty64'
  elsif ENV['XENIAL']
    config.vm.box = 'xenial-provisional'
  elsif ENV['CENTOS7']
    config.vm.box = 'developervms/centos7-64'
  else
    config.vm.box = 'centos6.4'
    config.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.4.2/centos64-x86_64-20140116.box'
  end

  config.vm.provider 'virtualbox' do |v|
    v.cpus = 4
    v.memory = 3000
  end

  config.vm.provision :shell, :path => 'shell/bootstrap.sh'
  config.vm.provision 'puppet'
end
