# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2:

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  provision_script = <<-eos
    apt-get install -y ruby-dev unzip rpm
	gem install fpm
  eos

	config.vm.provision "shell", inline: provision_script
end
