#!/bin/sh

set -e

case "$1" in
  purge|remove|abort-install)
    rm -rf "/usr/lib/jvm/java-8-oracle"
    rm -rf "/usr/lib/jvm/.java-8-oracle.jinfo"
    ;;
esac

#DEBHELPER#

exit 0

# vim: ts=2 sw=2
